# Generated by Django 2.0.1 on 2018-11-20 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wie', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workingtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingtime', models.IntegerField(blank=True, verbose_name='Arbeitszeit pro Woche')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Obj'),
        ),
        migrations.AddField(
            model_name='element',
            name='wie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Wie'),
        ),
    ]
