# Generated by Django 2.0.1 on 2018-11-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wie', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracking.Obj'),
        ),
        migrations.AddField(
            model_name='element',
            name='wie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracking.Wie'),
        ),
    ]
