# Generated by Django 2.0.1 on 2018-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='notiz',
            field=models.TextField(blank=True, default=None, verbose_name='Notiz'),
        ),
    ]
