# Generated by Django 2.0.1 on 2018-10-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20181021_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Start Time'),
        ),
    ]
