# Generated by Django 2.0.1 on 2018-11-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_element_kategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='kategorie',
        ),
    ]
