# Generated by Django 2.0.1 on 2018-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_workingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='time',
            field=models.IntegerField(blank=True, verbose_name='Arbeitszeit pro Woche'),
        ),
    ]
