# Generated by Django 2.0.1 on 2018-11-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_element_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='kategorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Kategorie'),
        ),
    ]
