# Generated by Django 2.0.1 on 2018-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_element_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat',
            field=models.CharField(max_length=200, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='kategorie',
            field=models.CharField(default=None, max_length=200, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='obj',
            field=models.CharField(default=None, max_length=200, verbose_name='Objekt'),
        ),
        migrations.AlterField(
            model_name='wie',
            name='wie',
            field=models.CharField(default=None, max_length=200, verbose_name='Wirtscahftszweig'),
        ),
    ]
