# Generated by Django 2.0.1 on 2018-11-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20181125_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat_element', models.CharField(default=None, max_length=200, verbose_name='Element')),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.KategorieElement'),
        ),
    ]
