# Generated by Django 2.0.1 on 2018-11-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20181125_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieElementSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.KategorieElement')),
            ],
        ),
    ]
