# Generated by Django 2.0.1 on 2018-11-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_kategorieelementsort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='kategorie',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
