# Generated by Django 2.0.1 on 2018-11-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20181127_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorieelementsort',
            name='kat_element',
        ),
        migrations.DeleteModel(
            name='KategorieElementSort',
        ),
    ]
