# Generated by Django 2.0.1 on 2018-11-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20181128_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementTOKat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.KategorieElement')),
                ('katgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Kategorie')),
            ],
        ),
    ]
