# Generated by Django 2.0.1 on 2018-12-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20181129_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='calc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Calc_Choices'),
        ),
    ]
