# Generated by Django 2.0.1 on 2018-12-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20181204_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='calc',
        ),
    ]
