# Generated by Django 2.0.1 on 2018-12-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_remove_element_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='calc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Calc_Choices'),
        ),
    ]
