# Generated by Django 2.0.1 on 2018-12-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_element_calc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wie', models.TextField(default=None, max_length=100)),
                ('obj', models.TextField(default=None, max_length=100)),
                ('calc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.Calc_Choices')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Categorie')),
                ('element', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.KategorieElement')),
            ],
        ),
    ]
