# Generated by Django 2.0.1 on 2018-12-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_elementtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementTOType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.KategorieElement')),
                ('typegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Categorie')),
            ],
        ),
    ]
