# Generated by Django 2.0.1 on 2018-12-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_elementtotype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementtest',
            name='calc',
        ),
        migrations.RemoveField(
            model_name='elementtest',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='elementtest',
            name='element',
        ),
        migrations.RemoveField(
            model_name='elementtotype',
            name='ele',
        ),
        migrations.RemoveField(
            model_name='elementtotype',
            name='typegroup',
        ),
        migrations.DeleteModel(
            name='Elementtest',
        ),
        migrations.DeleteModel(
            name='ElementTOType',
        ),
    ]
