# Generated by Django 2.0.1 on 2019-01-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20181207_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obj',
        ),
        migrations.DeleteModel(
            name='Wie',
        ),
    ]
