# Generated by Django 2.0.1 on 2019-01-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20190106_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='obj',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
