# Generated by Django 2.0.1 on 2019-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_remove_element_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat',
            field=models.CharField(max_length=200, verbose_name='Typ'),
        ),
    ]
