# Generated by Django 2.0.1 on 2018-11-20 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField(blank=True, max_length=200, verbose_name='Id')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('hours', models.IntegerField(blank=True, verbose_name='Workingtime')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('note', models.TextField(blank=True, max_length=200, verbose_name='Notiz')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Categorie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
