# Generated by Django 2.0.1 on 2019-01-06 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField(blank=True, max_length=200, verbose_name='Id')),
                ('title', models.TextField(max_length=200, verbose_name='Element')),
                ('type', models.TextField(max_length=200, verbose_name='type')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Workingtime')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('calc', models.TextField(blank=True, max_length=200, verbose_name='Calc')),
                ('note', models.TextField(blank=True, max_length=200, verbose_name='Notiz')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
