# Generated by Django 2.0.1 on 2018-12-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Element'),
        ),
    ]
