# Generated by Django 2.0.7 on 2019-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_calendarnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Notiz'),
        ),
    ]
