# Generated by Django 2.0.1 on 2018-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20181206_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='type',
            field=models.TextField(max_length=200, verbose_name='type'),
        ),
    ]
